name: Server Continuous Integration

on:
  push:
    branches-ignore: [master] # there is another action for push on master

defaults:
  run:
    working-directory: server

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      # Must be able to build using production dependencies for Heroku
      - name: Build using Production Dependencies
        run: |
          npm ci --only=prod
          npm run build

      - name: Install Dependencies
        run: npm i

      - name: Lint and Test
        run: |
          npm run lint
          npm test
